# Generated by Django 5.2.4 on 2025-09-04 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collectionsApp", "0006_remove_collection_products_collection_product_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("artist", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("rating", models.FloatField()),
                ("reviews", models.PositiveIntegerField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="products/"
                    ),
                ),
                ("badge", models.CharField(blank=True, max_length=50, null=True)),
                ("origin", models.CharField(max_length=100)),
                ("materials", models.CharField(max_length=200)),
                ("in_stock", models.BooleanField(default=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="collectionsApp.collection",
                    ),
                ),
            ],
        ),
    ]
