# Generated by Django 5.2.4 on 2025-09-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="collections/"
            ),
        ),
    ]
