# Generated by Django 5.2.4 on 2025-07-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsApp', '0002_collection_description_collection_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='img_url',
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='collections/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='products',
            field=models.IntegerField(default=True),
        ),
    ]
