# Generated by Django 5.2.4 on 2025-07-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectionsApp", "0003_remove_collection_img_url_collection_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="collections/"
            ),
        ),
    ]
