# Generated by Django 5.2.4 on 2025-09-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectionsApp", "0004_alter_collection_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
