# Generated by Django 5.2.4 on 2025-09-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectionsApp", "0005_collection_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="products",
        ),
        migrations.AddField(
            model_name="collection",
            name="product_count",
            field=models.IntegerField(default=0),
        ),
    ]
